apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:wj6ZqIA3pjOtPyQ8MG5UEuDxLv5+aWvLB+++Bw9x0nyb2VhHmIVImQd40xgafIKe0juxY2t90S/a4tBto95XuDJrIeXy4k89opKe7POfhwqH2Kj1IwGvNVw2IC6E0MCVepEkZf9K/HiMYlID01O9/IlDdpM+17aaH2ruz1ROa8KhBm4FWzkwBFWAgGBislKdvcXQi5EuRT9ArfnlElvU4nKv4vdIBremN2e0ALLrY4VurPk7ZODqb1uHKmOf5bymNfvUMC1bq0b2PbvgptSimJAKur+7OtDCHV8ggQ1tT3gJUiAA+A+G0tRbdXs=,iv:Y9aVxqSS6WWt6zFpMC7Ku4GgU7OKPhQdaG4O3XsjAyg=,tag:hNjD+WpZmp2XW8/gY9j+Dg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1rmqrk457amwa2xmesxma35flp0kzv0zfxfgj93flhy8crhc40vcqsulvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra2pjaDUwa291U0R5Q0hJ
            QStLVWE0U3RQdUd2akFIeVU5Sk43Wm1rcHhnCmkrSFdFY2hTbkFSdDh2UFNremFz
            THl3OG9wMVJhRm9OeG4yOXdvcG1EdEUKLS0tIDN4d2hTZnJlK0k5T1lBNU1jMEJl
            aU43NW5Hak5aQXEyZ21YdWRBRTZyaHcK22Umb/drVhRaox6VipyXSzmet0cdmKHk
            pwCQiaDgnKd+/+HSMCRiKy5WIWTGg73qVBqh86rUmX8fLkhl9VlWhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:42:58Z"
    mac: ENC[AES256_GCM,data:vALjYJ0b2H7duImVSL3w+YXowta3OTQZtEVPAUsbQpSUvTgxwEhrTq8fbpoyIsyIx+lUozATdFihrAujKSL5HOjJwvQ/Qv/azPdumcJVEnCK/xkzLchGFuIzs3t0aUVLdUDCwr00G5yVcoOdbjWpvoCXyiJkCH3XOoc/zeETLUA=,iv:3+n6bMtba3DYhvNCoHbPv1/Uw65N26H0WlYqSSNHN2I=,tag:zgj2IdtQMRtrf6jZuT6LMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
