apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      # securityContext:
      #   fsGroup: 1000 # node group ID
      #   runAsUser: 1000 # node user ID
      #   runAsGroup: 1000 # node group ID
      
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:2.10.2
          ports:
            - containerPort: 5678
              protocol: TCP
          envFrom:
            - configMapRef:
                name: n8n-configmap
            - secretRef:
                name: n8n-container-env

          securityContext:
            allowPrivilegeEscalation: false
            fsGroup: 1000 # node group ID
            runAsUser: 1000 # node user ID
            runAsGroup: 1000 # node group ID

          volumeMounts:
            - mountPath: "/home/node/.n8n"
              name: n8n-storage

        - name: postgres
          image: postgres:18.3
          ports:
            - containerPort: 5432
              protocol: TCP

          envFrom:
            - configMapRef:
                name: n8n-configmap
            - secretRef:
                name: n8n-container-env

          securityContext:
            allowPrivilegeEscalation: false
            fsGroup: 999 # postgres group ID
            runAsUser: 999 # postgres user ID
            runAsGroup: 999 # postgres group ID

          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: db-storage
              
      enableServiceLinks: false
      restartPolicy: Always

      volumes:
        - name: n8n-storage
          persistentVolumeClaim:
            claimName: n8n-storage-pvc
        - name: db-storage
          persistentVolumeClaim:
            claimName: n8n-db-storage-pvc

