apiVersion: v1
data:
    password: ENC[AES256_GCM,data:IDPqrStaBFoAwEKoc2qqloejoX+DjdMq,iv:6gMAr5fbHH720GC/YpYhTyhBcKmgoDMlRcii5ApnCXU=,tag:o88A49nqd4mmgGAH5qcF9A==,type:str]
    user: ENC[AES256_GCM,data:qBGeV9iVMLU/QiMU,iv:AcYbzUDASXWU3OD7udArWnQBrBl1MeetRgsBVQI+wP0=,tag:++96pB5UP6rj7fqiUawCsQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1rmqrk457amwa2xmesxma35flp0kzv0zfxfgj93flhy8crhc40vcqsulvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcDZHVkRZWXZSeHBJVjlN
            ekV1ZXFoanJVc3VwK1BHV3Q0RElwL3RzNkdrCkhKUmpjZUk3RFE4c296VUl1YTZ6
            Zm9mSU9LRFNjZnY0TmVFSEQzeFNxM0UKLS0tIHdUOVd6MDJlbnVnK0ZlNWZBMUFy
            YWZZN3Y1MDcwS2syYk4xNEZGeG1lV1kKFEjwpiUMvUpVHzjeG1t/QKlWd0cZfFp4
            xNcot72n5XX37Cy+hODO36YaeWcjs09Wo4chHeypg8tQ9D1+xkoMbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T16:57:33Z"
    mac: ENC[AES256_GCM,data:hqKWrXDG+SKOWLmwSDxS8Edgtuh2EoKZyYAwnLcIluIpXSxb27cpYOa2mL+WGShidZ00B7/JrKVaG52nIRkVYwjrCJ+7G/u1+qE7Q6DiSokoF7e0FWhtcMxpYXDKXp7u9BE+f+cVEFX8Tpmyn55yrXLAZ56hfCx/1ZkW5phRsjQ=,iv:5RbXuM3aLaXUPXgdt+4HvyZ6XwcSLkpNZHonWeUYhHo=,tag:FGuy/7zMQDw8V7Dbn9I5pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
