apiVersion: v1
data:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:e6iwDQmcjHD8KIjWxBkBpdjuF2wbZ2h2,iv:cqD0+fBdmomeEM6EgrL8vQG9h+wA71jNQ2EgnrdBgQc=,tag:hxI9BHST/Fn06vPYQoC3gg==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:3gOfwadudpztavv1,iv:nEHID9pqpMZwt4q4jmRLGqbEcnJgcAHjwcsO/VbgYQQ=,tag:jzfxx4zKwO3PKlmr1DR0pg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8CqBUJcEAb1TUBfD0KHoZ9fnK14qPGC5,iv:cBIswYFkMVYDfcXaBm72D8YXTw0Ag92TuBlT2nS2fOs=,tag:0Qlac6WJgCBJZWa8lXsXdg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:xnOevBwh1bSYDQeX,iv:BRXrcA4DqoFUQj+PphwAllSM+Qst/BYpL0psBL6ryUo=,tag:F1zHBQBI3UeZm6hdboQtDg==,type:str]
kind: Secret
metadata:
    name: n8n-container-env
sops:
    age:
        - recipient: age1rmqrk457amwa2xmesxma35flp0kzv0zfxfgj93flhy8crhc40vcqsulvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ3hxb2xMa3d1S2taYmRm
            OWFBSDhTN1lSK3ZnNmNQRTY4N2FHbk1NUmpNCkF3WXBmMVlCMzE1OWNENlhENlI4
            T0VDZFMyK0NtYlYrakRsWGVCQVFNVlEKLS0tIC9qQVJ0RTk4MzFDTzJNQjJHQ0Zq
            RE1BbzN4V3JkWFB2MEptMkhtL3pQRVUKXnDNKUzfgpTfuFS7SWGWA47hRZ+9aKmC
            ZQThjRFdNoCGX1mRK+st0Qmpc0xDrAfUXjG4SuFfherFbr73IXyIjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T00:16:32Z"
    mac: ENC[AES256_GCM,data:nUPC+sEahcujxzFzzubGzC9Gp4LnER2au2Am1fPIMOXQH8bI1MmMWmRtAwHFoEsHAZGfFh7ROEunPrYx+egBGF8DYsGtxA6HBVkyRK9XJRDdbtDXitIR/Kq8wc+aknmu1iMJK9KHvNGnyYvrZyr8d3mrkNs9dwkGfXeEiG+GzdI=,iv:t2KDvi6ciOaOhe4fnRr/fAto6JXGAPfywqPSUwEiJXs=,tag:bWc9PIQIZ7HkmL31pftjZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
