apiVersion: v1
data:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:lAZ5nL+2jKDqbE3yKGmkC/2Zi0lYWZgh,iv:9YkvlFKqwmwa/5CWmvTFVnAph5bgXRhC/yPl7XfTFPU=,tag:YJYCInQuGe+Ii8uRhuxi+g==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:I/60R3IKOJLwbZEg,iv:/UNWa/HljSujw2JPKYkH037KgzAk1vVJa/0Xrnm98eg=,tag:LchGyPs16tcXxFyPVM2n5Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PcpH5ttEqxg2XFIJEv6LJY9o86bWv5Y4,iv:Jr9s6oi1JQYu5rAPE+/L/HpkHY2dzZf1arJgMiYcocY=,tag:5TlrkBCXf57lMUOHOV9ZpA==,type:str]
kind: Secret
metadata:
    name: n8n-container-env
sops:
    age:
        - recipient: age1rmqrk457amwa2xmesxma35flp0kzv0zfxfgj93flhy8crhc40vcqsulvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOHJkb2tYcGQzQ3d0bVMr
            QXc5bWpNdjdyQzhVYkpZV1FISmVPT3daaHpBCjdjRUxGVEErc2Z0VWg2QitiVnNO
            MjUrZVJWLzg1YnFORnEzTGpBM2lMamcKLS0tIEZldkRiUWZFOUJQZEw3UGxZZVBW
            UkVmaVlKUGUzekwrREFaT0g4SjN1ZGcKkNZXpiYkc/AsZHz9JR20WlfYiXuahp/Z
            lCaZRtmZFQ/z4LneZCKTtNYU1iQ9XOnLce3g3Uqn5Fo4xjyobAaT0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T19:06:18Z"
    mac: ENC[AES256_GCM,data:QEN04MdXSQDfVv7zejKMk7O5euB4bqZsuk7URb6eVBzMKB6qp2SrphsyjLjwpQzmp3uIh8YkpWzB/49hPNhw44VAGGkWj8S+PMq9iULq6OxEkWNFxAarRoMnOOUZkst3H8vDLoXj0fekIwT7aEe/FG6B7hU0N4gGcP4fNLGOL0Y=,iv:2WPnVblEX7lgkLdxXEU2SDZrcFIbst4crHJK9wXMoXA=,tag:YxlT+5/qQjCPqWOh7BdrhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
