apiVersion: v1
data:
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:5LcuriSA/o7wpPFVHOrEjjhCXvKQeqgr,iv:aRb5n802f8fwvUY8EjF0NxPF1YTn5/jWERyVN2LAiuY=,tag:d0vGpklLNiMdUFJlMC8mSQ==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:s3dHg1QzhLZ4OYGN,iv:t2vyAqL2ONM5NTDcDhZMBwB2iyYxZwW/aBOZsAvqAos=,tag:e0oblBsbkp5LM0cQOnAPkQ==,type:str]
kind: Secret
metadata:
  name: n8n-container-env
  namespace: n8n
sops:
  age:
    - recipient: age1rmqrk457amwa2xmesxma35flp0kzv0zfxfgj93flhy8crhc40vcqsulvts
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dkdacUJzcUM2NTJDL0ZV
        cW9XN2c0Vy8yNk92blFmMEVkRncwWmNLcG0wCkxURUx2cm1QaWZPREZHYnRVNHJE
        NTVZYjlCQk1Mc2NBcFpHN1hiMmJjTzQKLS0tIHVERTdoZjJ2OGRBV00xNEd2UnY4
        M2lmdzBPUGppR0JIbVdSaGlWNkVUOEkKlBkKrabZ2SbgQwvcu8MThSbsgQ6v2SZq
        zC09YnQP2h6Pocx9WMXsN9LAG143LXN/Raa3HvuZT3/TCEk/Ni1zQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T18:33:18Z"
  mac: ENC[AES256_GCM,data:ZGmtQB3G1UkCNCLZsnNq/TEEGgpqKistB8dhjBP3dhrZHXkH4yM2UxCLIZzsDoqdt/8aGlNWZgr6pvq2U6oNg8zOirsumNoAyBNjsb1XD+iDjKKTxkQ0YIFOUjHOx6gp1ztGS3IsgWwnDYH8j/DBynLaj4Q+/fulK7I103CEM+M=,iv:Cvwpuh1R1Ze+QA+1bQO+jWdsoVGbMms7TxEdahNVEtM=,tag:3SCFb8KsCLx/yUAksUINRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
