apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:4YwQS2cb+Oq2WgERccnVEau8y1KdOJzD5a2tdgDVeLsy4ejbEb1S+LDaKJB5jlT5LyMuHHbITeOZPywJdb0rRSOqHgirqgmt5Zp+fV78E5Mk5rzE3f5O+9peZOz8ck924ln9gzDu+WGxjv0YvcC7hUq73hn2vkVtzEL3dTiS2dlU1ZNfk4bup7NlONVvFkdpH8q8oIRbsR+b4BSWm5AbhDzKM4Y0MEBPROjSBqlbSCRQqEN7YvADMv2grVpokjqniyjTPAz4DKKI2yBlbS9yojgg3Af6dKKNHfg7xZ5MqWtZpzqRvPntVwWZhnc=,iv:Xp/qUa9L/TFYGvTGTac5i0u1fJqYhnM1aFiRXpi0uG0=,tag:63BUGcPx2Zph/Jfe7emShg==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: jellyfin
sops:
  age:
    - recipient: age1rmqrk457amwa2xmesxma35flp0kzv0zfxfgj93flhy8crhc40vcqsulvts
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY2F0NUtUZ1pVRHJ1QXU1
        T3huVEpDM09KNDhzZW1wZ0ZYMFRNR0hyVkRBCmFsaVM0SXJweWZYQmZ4UVp4bENM
        OWppOVhudGtHakhuNWdyVEM4UkZkMUkKLS0tIEc2YUREWURhdXJOQlJSR044QlZT
        MlhVSmRHRWdmM2JNTjRmTzVkc2ZUQlEKEb2sfcdsUnS9HGip6yo6eSBPfJwyP9mI
        LqaAFMMfRG1Qc70KKkQJ7uHLDSgydeWIyblGHR0LJXcGcGweQgD38A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:05:30Z"
  mac: ENC[AES256_GCM,data:otzF3olwHFjBR713UM1ecJFqy6+JisVU455Wp+8abrb/VRuVX+QayvXzYwcxa4Saz6SBTN22Fq6fZP40iOVK5U5Q2lf4XUr26WASQTY/B7TkoP0r3DDwQP0EO+mdbxF6RkoUYI7tHmx9w3v4j+mefqyoDVCbjnkh9bqjPPhbu54=,iv:WhXsyk4obUQB1aq0PGV5b2keYPrkaAwQPRDSwG3x+H4=,tag:bkl3Pi8q2+31vZNUWhM9Wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
