apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000

      hostAliases:
        - ip: "192.168.0.110"
          hostnames:
            - "host.docker.internal"
      containers:
        - name: jellyfin
          image: ghcr.io/hotio/jellyfin:release-10.11.6
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 7359
              protocol: UDP

          envFrom:
            - configMapRef:
                name: jellyfin-config

          volumeMounts:
            - mountPath: "/config"
              name: jellyfin-config
            - mountPath: "/cache"
              name: jellyfin-cache
            - mountPath: "/home/yuri/jellyfin/media"
              name: jellyfin-media
            - mountPath: "/home/yuri/jellyfin/media2"
              name: jellyfin-media2

          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5

      restartPolicy: Always

      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: jellyfin-cache-pvc
        - name: jellyfin-media
          persistentVolumeClaim:
            claimName: jellyfin-media-pvc
        - name: jellyfin-media2
          persistentVolumeClaim:
            claimName: jellyfin-media2-pvc
